### ISSUE TITLE
About windows `npm run start-hot`

### ISSUE THREAD

**Issue by neighborhood999** [jigsawye/tcf2e-kktix-event-explorer-electron#1]
Windows user can't use `HOT=1 NODE_ENV=development electron .` that have something error.

Maybe in `READEME.md` add this optional for windows user：
`set HOT=1 && set NODE_ENV=development && electron .`

**Comment by jigsawye** [comment]
@neighborhood999 please check #2 , I can't test it because I haven't any PC

**Comment by neighborhood999** [comment]
@jigsawye OK！thank you.

**Comment by jigsawye** [comment]
@neighborhood999 does it work?
